In [1]:
import pandas as pd

df = pd.read_csv ('clean_data.csv',lineterminator='\n')
df

,id,product_name,product_description,price,location,page_id,create_time,category0,category1,category2,category3
0,243809c0-9cfc-4486-ad12-3b7a16605ba9,"Mirror wall art | in Wokingham, Berkshire | Gu...","Mirror wall art. Posted by Nisha in Dining, Li...",5.0,"Wokingham, Berkshire",1426704584,2022-02-26,Home & Garden,"Dining, Living Room Furniture","Mirrors, Clocks & Ornaments",NaN
1,1c58d3f9-8b93-47ea-9415-204fcc2a22e6,"Stainless Steel Food Steamer | in Inverness, H...",Morphy Richard’s (model no 48755)Stainless ste...,20.0,"Inverness, Highland",1426704579,2022-02-26,Home & Garden,Other Household Goods,NaN,NaN
2,860673f1-57f6-47ba-8d2f-13f9e05b8f9a,"Sun loungers | in Skegness, Lincolnshire | Gum...",I have 2 of these - collection only as I don’t...,20.0,"Skegness, Lincolnshire",1426704576,2022-02-26,Home & Garden,Garden & Patio,Outdoor Settings & Furniture,NaN
3,59948726-29be-4b35-ade5-bb2fd7331856,Coffee side table from Ammunition ammo box hai...,Great reclaimed army ammunition box used as co...,115.0,"Radstock, Somerset",1426704575,2022-02-26,Home & Garden,"Dining, Living Room Furniture",Other,NaN
4,16dbc860-696e-4cda-93f6-4dd4926573fb,Modern Shannon Sofa for sale at low cost | in ...,New Design Shannon Corner sofa 5 Seater Avail...,450.0,"Delph, Manchester",1426704570,2022-02-26,Home & Garden,"Dining, Living Room Furniture","Sofas, Armchairs & Suites",Private
...,...,...,...,...,...,...,...,...,...,...,...
7151,c4148656-78a9-4f3e-b393-134fdc5ef900,Sony PlayStation VR Move Bundle | in Acocks Gr...,Sony PlayStation VR Move Bundle353CASH ON COLL...,260.0,"Acocks Green, West Midlands",1422159237,2022-02-28,Video Games & Consoles,Consoles,PS4 (Sony Playstation 4),NaN
7152,564e3411-768d-4250-a624-b119d696f103,"Playstation VR V2 Bundle | in Acocks Green, We...",Playstation VR V2 Bundle355CASH ON COLLECTION ...,235.0,"Acocks Green, West Midlands",1422159464,2022-02-28,Video Games & Consoles,Consoles,PS4 (Sony Playstation 4),NaN
7153,2b0a652b-46a2-4297-b619-5efeeb222787,"Oculus quest 2 256gb | in Montrose, Angus | Gu...",Pick up only £250Comes with two pistols stocks...,250.0,"Montrose, Angus",1426668818,2022-02-28,Video Games & Consoles,Other Video Games & Consoles,NaN,NaN
7154,719fd40a-870e-4144-b324-55dff2e66fb4,Logitech driving force shifter | in Carrickfer...,Bought at christmas from currys retailing at £...,30.0,"Carrickfergus, County Antrim",1426699715,2022-02-28,Video Games & Consoles,Video Game Accessories,Other Video Game Accessories,NaN
7155,86d1806b-5575-4a7e-9160-f24f12be6c95,"20 GAMES & NINTENDO SWITCH BUNDLE | in Poole, ...",Nintendo Switch console only used 2/3 times. A...,450.0,"Poole, Dorset",1426699649,2022-02-28,Video Games & Consoles,Games,NaN,NaN

In [6]:
# we have to encode the categorical data so we can use techniques such as one hot encoding, label encoding, target encoding.
# Though label encoding is straight but it has the disadvantage that the numeric values can be misinterpreted by algorithms 
# as having some sort of hierarchy/order in them. We will thus use one hot encoding however this will result in many new columns.

df['category2'].describe()

count       4396
unique       297
top        Books
freq         220
Name: category2, dtype: object

In [7]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(handle_unknown='ignore')
enc_df = pd.DataFrame(enc.fit_transform(df[['category2']]).toarray())
new_df = df.join(enc_df)
new_df

,id,product_name,product_description,price,location,page_id,create_time,category0,category1,category2,...,288,289,290,291,292,293,294,295,296,297
0,243809c0-9cfc-4486-ad12-3b7a16605ba9,"Mirror wall art | in Wokingham, Berkshire | Gu...","Mirror wall art. Posted by Nisha in Dining, Li...",5.0,"Wokingham, Berkshire",1426704584,2022-02-26,Home & Garden,"Dining, Living Room Furniture","Mirrors, Clocks & Ornaments",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1c58d3f9-8b93-47ea-9415-204fcc2a22e6,"Stainless Steel Food Steamer | in Inverness, H...",Morphy Richard’s (model no 48755)Stainless ste...,20.0,"Inverness, Highland",1426704579,2022-02-26,Home & Garden,Other Household Goods,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,860673f1-57f6-47ba-8d2f-13f9e05b8f9a,"Sun loungers | in Skegness, Lincolnshire | Gum...",I have 2 of these - collection only as I don’t...,20.0,"Skegness, Lincolnshire",1426704576,2022-02-26,Home & Garden,Garden & Patio,Outdoor Settings & Furniture,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,59948726-29be-4b35-ade5-bb2fd7331856,Coffee side table from Ammunition ammo box hai...,Great reclaimed army ammunition box used as co...,115.0,"Radstock, Somerset",1426704575,2022-02-26,Home & Garden,"Dining, Living Room Furniture",Other,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,16dbc860-696e-4cda-93f6-4dd4926573fb,Modern Shannon Sofa for sale at low cost | in ...,New Design Shannon Corner sofa 5 Seater Avail...,450.0,"Delph, Manchester",1426704570,2022-02-26,Home & Garden,"Dining, Living Room Furniture","Sofas, Armchairs & Suites",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7151,c4148656-78a9-4f3e-b393-134fdc5ef900,Sony PlayStation VR Move Bundle | in Acocks Gr...,Sony PlayStation VR Move Bundle353CASH ON COLL...,260.0,"Acocks Green, West Midlands",1422159237,2022-02-28,Video Games & Consoles,Consoles,PS4 (Sony Playstation 4),...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7152,564e3411-768d-4250-a624-b119d696f103,"Playstation VR V2 Bundle | in Acocks Green, We...",Playstation VR V2 Bundle355CASH ON COLLECTION ...,235.0,"Acocks Green, West Midlands",1422159464,2022-02-28,Video Games & Consoles,Consoles,PS4 (Sony Playstation 4),...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7153,2b0a652b-46a2-4297-b619-5efeeb222787,"Oculus quest 2 256gb | in Montrose, Angus | Gu...",Pick up only £250Comes with two pistols stocks...,250.0,"Montrose, Angus",1426668818,2022-02-28,Video Games & Consoles,Other Video Games & Consoles,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
7154,719fd40a-870e-4144-b324-55dff2e66fb4,Logitech driving force shifter | in Carrickfer...,Bought at christmas from currys retailing at £...,30.0,"Carrickfergus, County Antrim",1426699715,2022-02-28,Video Games & Consoles,Video Game Accessories,Other Video Game Accessories,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7155,86d1806b-5575-4a7e-9160-f24f12be6c95,"20 GAMES & NINTENDO SWITCH BUNDLE | in Poole, ...",Nintendo Switch console only used 2/3 times. A...,450.0,"Poole, Dorset",1426699649,2022-02-28,Video Games & Consoles,Games,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [20]:
# using dummy values allows you to encode as many category columns as you would like and choose how to label the columns using a prefix
#, prefix=["category0_is", 'category1_is', 'category2_is', 'category3_is']
dum_df = pd.get_dummies(df, columns=['category0', 'category1', 'category2', 'category3'], prefix=["category0_is", 'category1_is', 'category2_is', 'category3_is'] )# merge with main df  on key values
dummies_df = df.merge(dum_df)
dummies_df

,id,product_name,product_description,price,location,page_id,create_time,category0,category1,category2,...,category3_is_ Toilets,category3_is_ Treadmills,category3_is_ Treadmills,category3_is_ Vibration Plates,category3_is_ Water Filters & Cartridges,category3_is_ Webcams,category3_is_ Weight Plates,category3_is_ Wine Racks & Barware,category3_is_ Wood Burners,category3_is_Amateur Radios
0,243809c0-9cfc-4486-ad12-3b7a16605ba9,"Mirror wall art | in Wokingham, Berkshire | Gu...","Mirror wall art. Posted by Nisha in Dining, Li...",5.0,"Wokingham, Berkshire",1426704584,2022-02-26,Home & Garden,"Dining, Living Room Furniture","Mirrors, Clocks & Ornaments",...,0,0,0,0,0,0,0,0,0,0
1,1c58d3f9-8b93-47ea-9415-204fcc2a22e6,"Stainless Steel Food Steamer | in Inverness, H...",Morphy Richard’s (model no 48755)Stainless ste...,20.0,"Inverness, Highland",1426704579,2022-02-26,Home & Garden,Other Household Goods,NaN,...,0,0,0,0,0,0,0,0,0,0
2,860673f1-57f6-47ba-8d2f-13f9e05b8f9a,"Sun loungers | in Skegness, Lincolnshire | Gum...",I have 2 of these - collection only as I don’t...,20.0,"Skegness, Lincolnshire",1426704576,2022-02-26,Home & Garden,Garden & Patio,Outdoor Settings & Furniture,...,0,0,0,0,0,0,0,0,0,0
3,59948726-29be-4b35-ade5-bb2fd7331856,Coffee side table from Ammunition ammo box hai...,Great reclaimed army ammunition box used as co...,115.0,"Radstock, Somerset",1426704575,2022-02-26,Home & Garden,"Dining, Living Room Furniture",Other,...,0,0,0,0,0,0,0,0,0,0
4,16dbc860-696e-4cda-93f6-4dd4926573fb,Modern Shannon Sofa for sale at low cost | in ...,New Design Shannon Corner sofa 5 Seater Avail...,450.0,"Delph, Manchester",1426704570,2022-02-26,Home & Garden,"Dining, Living Room Furniture","Sofas, Armchairs & Suites",...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7151,c4148656-78a9-4f3e-b393-134fdc5ef900,Sony PlayStation VR Move Bundle | in Acocks Gr...,Sony PlayStation VR Move Bundle353CASH ON COLL...,260.0,"Acocks Green, West Midlands",1422159237,2022-02-28,Video Games & Consoles,Consoles,PS4 (Sony Playstation 4),...,0,0,0,0,0,0,0,0,0,0
7152,564e3411-768d-4250-a624-b119d696f103,"Playstation VR V2 Bundle | in Acocks Green, We...",Playstation VR V2 Bundle355CASH ON COLLECTION ...,235.0,"Acocks Green, West Midlands",1422159464,2022-02-28,Video Games & Consoles,Consoles,PS4 (Sony Playstation 4),...,0,0,0,0,0,0,0,0,0,0
7153,2b0a652b-46a2-4297-b619-5efeeb222787,"Oculus quest 2 256gb | in Montrose, Angus | Gu...",Pick up only £250Comes with two pistols stocks...,250.0,"Montrose, Angus",1426668818,2022-02-28,Video Games & Consoles,Other Video Games & Consoles,NaN,...,0,0,0,0,0,0,0,0,0,0
7154,719fd40a-870e-4144-b324-55dff2e66fb4,Logitech driving force shifter | in Carrickfer...,Bought at christmas from currys retailing at £...,30.0,"Carrickfergus, County Antrim",1426699715,2022-02-28,Video Games & Consoles,Video Game Accessories,Other Video Game Accessories,...,0,0,0,0,0,0,0,0,0,0
7155,86d1806b-5575-4a7e-9160-f24f12be6c95,"20 GAMES & NINTENDO SWITCH BUNDLE | in Poole, ...",Nintendo Switch console only used 2/3 times. A...,450.0,"Poole, Dorset",1426699649,2022-02-28,Video Games & Consoles,Games,NaN,...,0,0,0,0,0,0,0,0,0,0

In [25]:
dum2_df = pd.get_dummies(df, columns=['category0', 'category1'], prefix=["category0_is", 'category1_is'] )# merge with main df  on key values
cat1_2_df = df.merge(dum2_df)
cat1_2_df

,id,product_name,product_description,price,location,page_id,create_time,category0,category1,category2,...,category1_is_ Washer Dryers,category1_is_ Washing Machines,category1_is_ Watches,category1_is_ Water Sports,category1_is_ Wedding Clothes & Accessories,category1_is_ Winter Sports,category1_is_ Women's Accessories,category1_is_ Women's Clothing,category1_is_ Women's Shoes,category1_is_ Wood & Timber
0,243809c0-9cfc-4486-ad12-3b7a16605ba9,"Mirror wall art | in Wokingham, Berkshire | Gu...","Mirror wall art. Posted by Nisha in Dining, Li...",5.0,"Wokingham, Berkshire",1426704584,2022-02-26,Home & Garden,"Dining, Living Room Furniture","Mirrors, Clocks & Ornaments",...,0,0,0,0,0,0,0,0,0,0
1,1c58d3f9-8b93-47ea-9415-204fcc2a22e6,"Stainless Steel Food Steamer | in Inverness, H...",Morphy Richard’s (model no 48755)Stainless ste...,20.0,"Inverness, Highland",1426704579,2022-02-26,Home & Garden,Other Household Goods,NaN,...,0,0,0,0,0,0,0,0,0,0
2,860673f1-57f6-47ba-8d2f-13f9e05b8f9a,"Sun loungers | in Skegness, Lincolnshire | Gum...",I have 2 of these - collection only as I don’t...,20.0,"Skegness, Lincolnshire",1426704576,2022-02-26,Home & Garden,Garden & Patio,Outdoor Settings & Furniture,...,0,0,0,0,0,0,0,0,0,0
3,59948726-29be-4b35-ade5-bb2fd7331856,Coffee side table from Ammunition ammo box hai...,Great reclaimed army ammunition box used as co...,115.0,"Radstock, Somerset",1426704575,2022-02-26,Home & Garden,"Dining, Living Room Furniture",Other,...,0,0,0,0,0,0,0,0,0,0
4,16dbc860-696e-4cda-93f6-4dd4926573fb,Modern Shannon Sofa for sale at low cost | in ...,New Design Shannon Corner sofa 5 Seater Avail...,450.0,"Delph, Manchester",1426704570,2022-02-26,Home & Garden,"Dining, Living Room Furniture","Sofas, Armchairs & Suites",...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7151,c4148656-78a9-4f3e-b393-134fdc5ef900,Sony PlayStation VR Move Bundle | in Acocks Gr...,Sony PlayStation VR Move Bundle353CASH ON COLL...,260.0,"Acocks Green, West Midlands",1422159237,2022-02-28,Video Games & Consoles,Consoles,PS4 (Sony Playstation 4),...,0,0,0,0,0,0,0,0,0,0
7152,564e3411-768d-4250-a624-b119d696f103,"Playstation VR V2 Bundle | in Acocks Green, We...",Playstation VR V2 Bundle355CASH ON COLLECTION ...,235.0,"Acocks Green, West Midlands",1422159464,2022-02-28,Video Games & Consoles,Consoles,PS4 (Sony Playstation 4),...,0,0,0,0,0,0,0,0,0,0
7153,2b0a652b-46a2-4297-b619-5efeeb222787,"Oculus quest 2 256gb | in Montrose, Angus | Gu...",Pick up only £250Comes with two pistols stocks...,250.0,"Montrose, Angus",1426668818,2022-02-28,Video Games & Consoles,Other Video Games & Consoles,NaN,...,0,0,0,0,0,0,0,0,0,0
7154,719fd40a-870e-4144-b324-55dff2e66fb4,Logitech driving force shifter | in Carrickfer...,Bought at christmas from currys retailing at £...,30.0,"Carrickfergus, County Antrim",1426699715,2022-02-28,Video Games & Consoles,Video Game Accessories,Other Video Game Accessories,...,0,0,0,0,0,0,0,0,0,0
7155,86d1806b-5575-4a7e-9160-f24f12be6c95,"20 GAMES & NINTENDO SWITCH BUNDLE | in Poole, ...",Nintendo Switch console only used 2/3 times. A...,450.0,"Poole, Dorset",1426699649,2022-02-28,Video Games & Consoles,Games,NaN,...,0,0,0,0,0,0,0,0,0,0

In [29]:
dum_df = pd.get_dummies(df, columns=['category0'], prefix=["category0_is"] )# merge with main df  on key values
cat0_df = df.merge(dum_df)
cat0_df

,id,product_name,product_description,price,location,page_id,create_time,category0,category1,category2,...,category0_is_Computers & Software,category0_is_DIY Tools & Materials,category0_is_Health & Beauty,category0_is_Home & Garden,"category0_is_Music, Films, Books & Games",category0_is_Office Furniture & Equipment,category0_is_Other Goods,"category0_is_Phones, Mobile Phones & Telecoms","category0_is_Sports, Leisure & Travel",category0_is_Video Games & Consoles
0,243809c0-9cfc-4486-ad12-3b7a16605ba9,"Mirror wall art | in Wokingham, Berkshire | Gu...","Mirror wall art. Posted by Nisha in Dining, Li...",5.0,"Wokingham, Berkshire",1426704584,2022-02-26,Home & Garden,"Dining, Living Room Furniture","Mirrors, Clocks & Ornaments",...,0,0,0,1,0,0,0,0,0,0
1,1c58d3f9-8b93-47ea-9415-204fcc2a22e6,"Stainless Steel Food Steamer | in Inverness, H...",Morphy Richard’s (model no 48755)Stainless ste...,20.0,"Inverness, Highland",1426704579,2022-02-26,Home & Garden,Other Household Goods,NaN,...,0,0,0,1,0,0,0,0,0,0
2,860673f1-57f6-47ba-8d2f-13f9e05b8f9a,"Sun loungers | in Skegness, Lincolnshire | Gum...",I have 2 of these - collection only as I don’t...,20.0,"Skegness, Lincolnshire",1426704576,2022-02-26,Home & Garden,Garden & Patio,Outdoor Settings & Furniture,...,0,0,0,1,0,0,0,0,0,0
3,59948726-29be-4b35-ade5-bb2fd7331856,Coffee side table from Ammunition ammo box hai...,Great reclaimed army ammunition box used as co...,115.0,"Radstock, Somerset",1426704575,2022-02-26,Home & Garden,"Dining, Living Room Furniture",Other,...,0,0,0,1,0,0,0,0,0,0
4,16dbc860-696e-4cda-93f6-4dd4926573fb,Modern Shannon Sofa for sale at low cost | in ...,New Design Shannon Corner sofa 5 Seater Avail...,450.0,"Delph, Manchester",1426704570,2022-02-26,Home & Garden,"Dining, Living Room Furniture","Sofas, Armchairs & Suites",...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7151,c4148656-78a9-4f3e-b393-134fdc5ef900,Sony PlayStation VR Move Bundle | in Acocks Gr...,Sony PlayStation VR Move Bundle353CASH ON COLL...,260.0,"Acocks Green, West Midlands",1422159237,2022-02-28,Video Games & Consoles,Consoles,PS4 (Sony Playstation 4),...,0,0,0,0,0,0,0,0,0,1
7152,564e3411-768d-4250-a624-b119d696f103,"Playstation VR V2 Bundle | in Acocks Green, We...",Playstation VR V2 Bundle355CASH ON COLLECTION ...,235.0,"Acocks Green, West Midlands",1422159464,2022-02-28,Video Games & Consoles,Consoles,PS4 (Sony Playstation 4),...,0,0,0,0,0,0,0,0,0,1
7153,2b0a652b-46a2-4297-b619-5efeeb222787,"Oculus quest 2 256gb | in Montrose, Angus | Gu...",Pick up only £250Comes with two pistols stocks...,250.0,"Montrose, Angus",1426668818,2022-02-28,Video Games & Consoles,Other Video Games & Consoles,NaN,...,0,0,0,0,0,0,0,0,0,1
7154,719fd40a-870e-4144-b324-55dff2e66fb4,Logitech driving force shifter | in Carrickfer...,Bought at christmas from currys retailing at £...,30.0,"Carrickfergus, County Antrim",1426699715,2022-02-28,Video Games & Consoles,Video Game Accessories,Other Video Game Accessories,...,0,0,0,0,0,0,0,0,0,1
7155,86d1806b-5575-4a7e-9160-f24f12be6c95,"20 GAMES & NINTENDO SWITCH BUNDLE | in Poole, ...",Nintendo Switch console only used 2/3 times. A...,450.0,"Poole, Dorset",1426699649,2022-02-28,Video Games & Consoles,Games,NaN,...,0,0,0,0,0,0,0,0,0,1

In [34]:
dum_df = pd.get_dummies(df, columns=['category1'], prefix=["category1_is"] )# merge with main df  on key values
cat1_df = df.merge(dum_df)
cat1_df

,id,product_name,product_description,price,location,page_id,create_time,category0,category1,category2,...,category1_is_ Washer Dryers,category1_is_ Washing Machines,category1_is_ Watches,category1_is_ Water Sports,category1_is_ Wedding Clothes & Accessories,category1_is_ Winter Sports,category1_is_ Women's Accessories,category1_is_ Women's Clothing,category1_is_ Women's Shoes,category1_is_ Wood & Timber
0,243809c0-9cfc-4486-ad12-3b7a16605ba9,"Mirror wall art | in Wokingham, Berkshire | Gu...","Mirror wall art. Posted by Nisha in Dining, Li...",5.0,"Wokingham, Berkshire",1426704584,2022-02-26,Home & Garden,"Dining, Living Room Furniture","Mirrors, Clocks & Ornaments",...,0,0,0,0,0,0,0,0,0,0
1,1c58d3f9-8b93-47ea-9415-204fcc2a22e6,"Stainless Steel Food Steamer | in Inverness, H...",Morphy Richard’s (model no 48755)Stainless ste...,20.0,"Inverness, Highland",1426704579,2022-02-26,Home & Garden,Other Household Goods,NaN,...,0,0,0,0,0,0,0,0,0,0
2,860673f1-57f6-47ba-8d2f-13f9e05b8f9a,"Sun loungers | in Skegness, Lincolnshire | Gum...",I have 2 of these - collection only as I don’t...,20.0,"Skegness, Lincolnshire",1426704576,2022-02-26,Home & Garden,Garden & Patio,Outdoor Settings & Furniture,...,0,0,0,0,0,0,0,0,0,0
3,59948726-29be-4b35-ade5-bb2fd7331856,Coffee side table from Ammunition ammo box hai...,Great reclaimed army ammunition box used as co...,115.0,"Radstock, Somerset",1426704575,2022-02-26,Home & Garden,"Dining, Living Room Furniture",Other,...,0,0,0,0,0,0,0,0,0,0
4,16dbc860-696e-4cda-93f6-4dd4926573fb,Modern Shannon Sofa for sale at low cost | in ...,New Design Shannon Corner sofa 5 Seater Avail...,450.0,"Delph, Manchester",1426704570,2022-02-26,Home & Garden,"Dining, Living Room Furniture","Sofas, Armchairs & Suites",...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7151,c4148656-78a9-4f3e-b393-134fdc5ef900,Sony PlayStation VR Move Bundle | in Acocks Gr...,Sony PlayStation VR Move Bundle353CASH ON COLL...,260.0,"Acocks Green, West Midlands",1422159237,2022-02-28,Video Games & Consoles,Consoles,PS4 (Sony Playstation 4),...,0,0,0,0,0,0,0,0,0,0
7152,564e3411-768d-4250-a624-b119d696f103,"Playstation VR V2 Bundle | in Acocks Green, We...",Playstation VR V2 Bundle355CASH ON COLLECTION ...,235.0,"Acocks Green, West Midlands",1422159464,2022-02-28,Video Games & Consoles,Consoles,PS4 (Sony Playstation 4),...,0,0,0,0,0,0,0,0,0,0
7153,2b0a652b-46a2-4297-b619-5efeeb222787,"Oculus quest 2 256gb | in Montrose, Angus | Gu...",Pick up only £250Comes with two pistols stocks...,250.0,"Montrose, Angus",1426668818,2022-02-28,Video Games & Consoles,Other Video Games & Consoles,NaN,...,0,0,0,0,0,0,0,0,0,0
7154,719fd40a-870e-4144-b324-55dff2e66fb4,Logitech driving force shifter | in Carrickfer...,Bought at christmas from currys retailing at £...,30.0,"Carrickfergus, County Antrim",1426699715,2022-02-28,Video Games & Consoles,Video Game Accessories,Other Video Game Accessories,...,0,0,0,0,0,0,0,0,0,0
7155,86d1806b-5575-4a7e-9160-f24f12be6c95,"20 GAMES & NINTENDO SWITCH BUNDLE | in Poole, ...",Nintendo Switch console only used 2/3 times. A...,450.0,"Poole, Dorset",1426699649,2022-02-28,Video Games & Consoles,Games,NaN,...,0,0,0,0,0,0,0,0,0,0

In [30]:
#lets test it with only dummy variables for category 0
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn import metrics

features = ['price','id','product_name', 'product_description','location', 'page_id', 'create_time', 'category0', 'category1', 'category2', 'category3']

#X = data.drop('price',axis =1)
X = cat0_df.drop(columns = features)
y = cat0_df['price']

train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.3)

print(train_X.shape)
print(train_y.shape)
print(test_X.shape)
print(test_y.shape)

(5009, 13)
(5009,)
(2147, 13)
(2147,)

In [31]:
model = linear_model.LinearRegression()

model.fit(train_X, train_y)
y_pred = model.predict(test_X)

In [33]:
from sklearn.metrics import mean_squared_error, r2_score 
import numpy as np

def calculate_metrics(y_test, y_pred):  
    ''' 
    y_test:- ground truth 
    y_pred:- model predict  
    '''
    mse = mean_squared_error(test_y, y_pred) 
    rmse = np.sqrt(mse) 
    r2_scores = r2_score(test_y, y_pred) 
    
    print("MSE: ", mse) 
    print("RMSE: ", rmse) 
    print("R2_score: ", r2_scores) 
    
calculate_metrics(test_y, y_pred)

MSE:  667469343.9884115
RMSE:  25835.42807828838
R2_score:  -0.13715853989496574

In [37]:
#lets test it with only dummy variables for category 1. This has more categories so maybe more inaccurate
features = ['price','id','product_name', 'product_description','location', 'page_id', 'create_time', 'category0', 'category1', 'category2', 'category3']

#X = data.drop('price',axis =1)
X = cat1_df.drop(columns = features)
y = cat1_df['price']

train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.3)

print(train_X.shape)
print(train_y.shape)
print(test_X.shape)
print(test_y.shape)

(5009, 115)
(5009,)
(2147, 115)
(2147,)

In [38]:
model = linear_model.LinearRegression()

model.fit(train_X, train_y)
y_pred = model.predict(test_X)
def calculate_metrics(y_test, y_pred):  
    ''' 
    y_test:- ground truth 
    y_pred:- model predict  
    '''
    mse = mean_squared_error(test_y, y_pred) 
    rmse = np.sqrt(mse) 
    r2_scores = r2_score(test_y, y_pred) 
    
    print("MSE: ", mse) 
    print("RMSE: ", rmse) 
    print("R2_score: ", r2_scores) 
    
calculate_metrics(test_y, y_pred)

MSE:  1.6788515807707584e+29
RMSE:  409737913887738.56
R2_score:  -2.905631740647323e+20